In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pickle
import seaborn as sns

pd.options.display.max_columns = None
plt.style.use("fivethirtyeight")
plt.rcParams["figure.dpi"] = 150

In [25]:
X_train, X_ivs, y_train, col_names = pickle.load(open("../data/drd2_data.pickle", "rb"))

In [49]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler 

alphas = np.arange(0.001, 1000, 50)   
coefs_list = []
scale = StandardScaler()
X_scale = scale.fit_transform(X_train)


for alpha in alphas:
    lasso = Lasso(alpha=alpha)
    lasso.fit(X_scale, y_train)
    coefs = lasso.coef_
    coefs_list.append(coefs)


In [38]:
coefs_list

[array([-0.        , -0.        , -0.        , ..., -0.00468327,
         0.00241709, -0.        ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([ 0.,  0.,  0., ...,  0., -0.,  0.]),
 array([ 0.,  0.,  0., ...,  0., -0.,  0.]),
 array([ 0.,  0.,  0., ...,  0., -0.,  0.]),
 array([ 0.,  0.,  0., ...,  0., -0.,  0.]),
 array([ 0.,  0.,  0., ...,  0., -0.,  0.])]

In [50]:
coef_df = pd.DataFrame(coefs_list)
coef_df["alpha"] = alphas
coef_df

0    1    2    3    4    5    6    7    8    9   10   11        12   13  \
0  -0.0 -0.0 -0.0  0.0 -0.0  0.0  0.0 -0.0 -0.0 -0.0  0.0  0.0  0.002379  0.0   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   

     14   15   16   17        18   19        20        21   22        23   24  \
0   0.0  0.0  0.0  0.0  0.016542  0.0 -0.009248 -0.002217 -0.0 -0.014319  0.0   
1   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
2   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
3   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
4   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
5   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
6   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
7   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
8   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
9   0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
10  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
11  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
12  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
13  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
14  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
15  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
16  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
17  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
18  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   
19  0.0  0.0  0.0 -0.0  0.000000  0.0 -0.000000  0.000000  0.0 -0.000000  0.0   

     25        26   27   28   29   30   31   32   33   34   35   36   37   38  \
0  -0.0  0.015924  0.0  0.0  0.0  0.0  0.0  0.0 -0.0  0.0  0.0  0.0  0.0  0.0   
1   0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0   
2   0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0   
3   0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0   
4   0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0   
5   0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0   
6   0.0  0.000000  0.0  0.0  0.0  0

In [54]:
coef_df.columns = [f"PCA{i}" for i in range(0, coef_df.shape[1])]

In [55]:
coef_df

PCA0  PCA1  PCA2  PCA3  PCA4  PCA5  PCA6  PCA7  PCA8  PCA9  PCA10  PCA11  \
0   -0.0  -0.0  -0.0   0.0  -0.0   0.0   0.0  -0.0  -0.0  -0.0    0.0    0.0   
1    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
2    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
3    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
4    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
5    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
6    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
7    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
8    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
9    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
10   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
11   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
12   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
13   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
14   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
15   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
16   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
17   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
18   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   
19   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0   

       PCA12  PCA13  PCA14  PCA15  PCA16  PCA17     PCA18  PCA19     PCA20  \
0   0.002379    0.0    0.0    0.0    0.0    0.0  0.016542    0.0 -0.009248   
1   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
2   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
3   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
4   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
5   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
6   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
7   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
8   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
9   0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
10  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
11  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
12  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
13  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
14  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
15  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
16  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
17  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
18  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   
19  0.000000    0.0    0.0    0.0    0.0   -0.0  0.000000    0.0 -0.000000   

       PCA21  PCA22     PCA23  PCA24  PCA25     PCA26  PCA27  PCA28  PCA29  \
0  -0.002217   -0.0 -0.014319    0.0   -0.0  0.015924    0.0    0.0    0.0   
1   0.000000    0.0 -0.000000    0.0    0.0  0.000000    0.0    0.0    0.0   
2   0.000000    0.0 -0.000000    0.0    0.0  0.000000    0.0    0.0    0.0   
3   0.000000    0.0 -0.000000    0.0    0.0  0.000000    0.0    0.0    0.0   
4   0.000000    0.0 -0.000000    0.0    0.0  0.000000    0.0    0.0    0.0   
5   0.000000    0.0 -0.000000    0.0    0.0  0.000000    0.0    0.0    0.0   
6   0.000000    0.0 -0.000000    0.0    0.0  0.000000    0.0    0.0    0.0   
7   0.000000    0.0 -0.000000    0.0    0.0  0.000000    0.0

In [51]:
for col in coef_df.columns:
    plt.plot(alphas, coef_df[col])

plt.xscale("log")
plt.show()